Repository Royal-Navy/design-system-docs, pull requests merged in 2021-11, with the labels that each got.

#404 chore(NVM): Upgrade to latest LTS (16.x.x)
  .nvmrc
Labels: Type: Development

#410 ci(GHA): Change workflow trigger
  .github/workflows/build_and_test_feature.yml
  cypress/specs/docs/homepage.spec.ts
Labels: Type: Devops

#420 ci(GHA): Add failure notifications to release workflows
  .github/workflows/manual_release.yml
  .github/workflows/release.yml
Labels: Type: Devops, Size: Small
