Repository Royal-Navy/design-system-docs, pull requests merged in 2021-07, with the labels that each got.

#162 ci(SonarCloud): Exclude stories from coverage
  sonar-project.properties
Labels: Type: Devops

#158 feat(OnThisPage): Add component
  babel.config.js
  components/helpers.ts
  components/presenters/OnThisPage/OnThisPage.stories.tsx
  components/presenters/OnThisPage/OnThisPage.test.tsx
  components/presenters/OnThisPage/OnThisPage.tsx
  components/presenters/OnThisPage/OnThisPageItem.tsx
  components/presenters/OnThisPage/index.ts
  components/presenters/OnThisPage/partials/StyledHeading.tsx
  components/presenters/OnThisPage/partials/StyledItem.tsx
  components/presenters/OnThisPage/partials/StyledItems.tsx
  components/presenters/OnThisPage/partials/StyledOnThisPage.tsx
Labels: Type: Development

#161 ci(GHA): Remove space in label-name value
  .github/workflows/project_issues.yml
Labels: Type: Bug, Type: Devops

#165 feat(Masthead): Create base component
  .storybook/main.js
  components/presenters/Docs/Badge/Badge.stories.tsx
  components/presenters/Docs/Masthead/Masthead.stories.tsx
  components/presenters/Docs/Masthead/Masthead.test.tsx
  components/presenters/Docs/Masthead/Masthead.tsx
  components/presenters/Docs/Masthead/MastheadMenu.tsx
  components/presenters/Docs/Masthead/MastheadMenuItem.tsx
  components/presenters/Docs/Masthead/MastheadSubMenu.tsx
  components/presenters/Docs/Masthead/MastheadSubMenuItem.tsx
  components/presenters/Docs/Masthead/index.ts
  components/presenters/Docs/Masthead/partials/StyledExpandButton.tsx
  components/presenters/Docs/Masthead/partials/StyledMasthead.tsx
  components/presenters/Docs/Masthead/partials/StyledMastheadMenu.tsx
  components/presenters/Docs/Masthead/partials/StyledMastheadMenuItem.tsx
  components/presenters/Docs/Masthead/partials/StyledMastheadMenuLink.tsx
  components/presenters/Docs/Masthead/partials/StyledMastheadSubMenu.tsx
  components/presenters/Docs/Masthead/partials/StyledMenuButton.tsx
  components/presenters/Docs/PageBanner/PageBanner.stories.tsx
  components/presenters/Framework/ApiTable/ApiTable.stories.tsx
  components/presenters/Framework/CodeBlock/CodeBlock.stories.tsx
  components/presenters/Framework/Hero/Hero.stories.tsx
  components/presenters/Framework/LiveExample/LiveExample.stories.tsx
  components/presenters/Framework/Masthead/Masthead.stories.tsx
  components/presenters/Framework/Sidebar/Sidebar.stories.tsx
  index.d.ts
  jest.config.js
  jest/__mocks__/svgrMock.js
  next-env.d.ts
  next.config.js
  package.json
  public/RNDSLogo.svg
  yarn.lock
Labels: Type: Development, Type: Enhancement

#167 feat(ContentBanner): Create base component
  components/presenters/Docs/ContentBanner/ContentBanner.stories.tsx
  components/presenters/Docs/ContentBanner/ContentBanner.test.tsx
  components/presenters/Docs/ContentBanner/ContentBanner.tsx
  components/presenters/Docs/ContentBanner/index.ts
  components/presenters/Docs/ContentBanner/partials/StyledContentBanner.tsx
  components/presenters/Docs/ContentBanner/partials/StyledDescription.tsx
  components/presenters/Docs/ContentBanner/partials/StyledTitle.tsx
Labels: Type: Development, Type: Enhancement

#166 Add `Sidebar` presentational component
  components/presenters/Docs/OnThisPage/OnThisPage.stories.tsx
  components/presenters/Docs/OnThisPage/OnThisPage.test.tsx
  components/presenters/Docs/OnThisPage/OnThisPage.tsx
  components/presenters/Docs/OnThisPage/OnThisPageItem.tsx
  components/presenters/Docs/OnThisPage/index.ts
  components/presenters/Docs/OnThisPage/partials/StyledHeading.tsx
  components/presenters/Docs/OnThisPage/partials/StyledItem.tsx
  components/presenters/Docs/OnThisPage/partials/StyledItems.tsx
  components/presenters/Docs/OnThisPage/partials/StyledOnThisPage.tsx
  components/presenters/Docs/Sidebar/Sidebar.stories.tsx
  components/presenters/Docs/Sidebar/Sidebar.test.tsx
  components/presenters/Docs/Sidebar/Sidebar.tsx
  components/presenters/Docs/Sidebar/SidebarFilter.tsx
  components/presenters/Docs/Sidebar/SidebarMenu.tsx
  components/presenters/Docs/Sidebar/SidebarMenuItem.tsx
  components/presenters/Docs/Sidebar/SidebarOverview.tsx
  components/presenters/Docs/Sidebar/SidebarOverviewMenuItem.tsx
  components/presenters/Docs/Sidebar/index.ts
  components/presenters/Docs/Sidebar/partials/StyledFilter.tsx
  components/presenters/Docs/Sidebar/partials/StyledFilterButton.tsx
  components/presenters/Docs/Sidebar/partials/StyledFilterEndAdornment.tsx
  components/presenters/Docs/Sidebar/partials/StyledFilterInput.tsx
  components/presenters/Docs/Sidebar/partials/StyledFilterInputWrapper.tsx
  components/presenters/Docs/Sidebar/partials/StyledFilterOuterWrapper.tsx
  components/presenters/Docs/Sidebar/partials/StyledNavLink.tsx
  components/presenters/Docs/Sidebar/partials/StyledNavList.tsx
  components/presenters/Docs/Sidebar/partials/StyledNavSection.tsx
  components/presenters/Docs/Sidebar/partials/StyledNavSectionTitle.tsx
  components/presenters/Docs/Sidebar/partials/StyledOverview.tsx
  components/presenters/Docs/Sidebar/partials/StyledOverviewNavLink.tsx
  components/presenters/Docs/Sidebar/partials/StyledOverviewTitle.tsx
  components/presenters/Docs/Sidebar/partials/StyledSidebar.tsx
  components/presenters/Docs/Sidebar/partials/StyledSidebarMenu.tsx
  components/presenters/Docs/Sidebar/partials/StyledSidebarMenuItem.tsx
  components/presenters/Docs/Sidebar/partials/StyledTitle.tsx
  package.json
  yarn.lock
Labels: Type: Development

#168 Add `Footer` component
  components/presenters/Docs/Footer/Footer.stories.tsx
  components/presenters/Docs/Footer/Footer.test.tsx
  components/presenters/Docs/Footer/Footer.tsx
  components/presenters/Docs/Footer/FooterExternalLink.tsx
  components/presenters/Docs/Footer/index.ts
  components/presenters/Docs/Footer/partials/StyledCopyright.tsx
  components/presenters/Docs/Footer/partials/StyledDescription.tsx
  components/presenters/Docs/Footer/partials/StyledExternalLink.tsx
  components/presenters/Docs/Footer/partials/StyledFooter.tsx
  components/presenters/Docs/Footer/partials/StyledFooterLogo.tsx
  components/presenters/Docs/Footer/partials/StyledLinkList.tsx
  components/presenters/Docs/Footer/partials/StyledNelsonLogoClip.tsx
  components/presenters/Docs/Footer/partials/StyledRNDSLogo.tsx
  components/presenters/Docs/Footer/partials/StyledSubFooter.tsx
  jest.config.js
  package.json
  public/NavyDigitalServicesLogo.svg
  public/NelsonLogoClip.svg
  yarn.lock
Labels: Type: Development

#170 feat(Footer): Implement mobile CSS
  components/presenters/Docs/Footer/Footer.tsx
  components/presenters/Docs/Footer/partials/StyledCopyright.tsx
  components/presenters/Docs/Footer/partials/StyledDescription.tsx
  components/presenters/Docs/Footer/partials/StyledFooter.tsx
  components/presenters/Docs/Footer/partials/StyledFooterLogo.tsx
  components/presenters/Docs/Footer/partials/StyledLinkList.tsx
  components/presenters/Docs/Footer/partials/StyledNelsonLogoClip.tsx
  components/presenters/Docs/Footer/partials/StyledSubFooter.tsx
Labels: Type: Development

#171 feat(Masthead): Add mobile navigation
  components/presenters/Docs/Masthead/Masthead.stories.tsx
  components/presenters/Docs/Masthead/Masthead.test.tsx
  components/presenters/Docs/Masthead/Masthead.tsx
  components/presenters/Docs/Masthead/MastheadMenu.tsx
  components/presenters/Docs/Masthead/MastheadMenuItem.tsx
  components/presenters/Docs/Masthead/MastheadSubMenuItem.tsx
  components/presenters/Docs/Masthead/partials/StyledButton.tsx
  components/presenters/Docs/Masthead/partials/StyledExpandButton.tsx
  components/presenters/Docs/Masthead/partials/StyledMasthead.tsx
  components/presenters/Docs/Masthead/partials/StyledMastheadMenu.tsx
  components/presenters/Docs/Masthead/partials/StyledMastheadMenuItem.tsx
  components/presenters/Docs/Masthead/partials/StyledMastheadMobile.tsx
  components/presenters/Docs/Masthead/partials/StyledMastheadSubMenu.tsx
  components/presenters/Docs/Masthead/partials/StyledMastheadSubMenuItem.tsx
  components/presenters/Docs/Masthead/partials/StyledMenuButton.tsx
  public/RNDSMobileLogo.svg
Labels: Type: Development, Type: Enhancement

#176 feat(GraphQL): Add Contentful queries
  components/presenters/Docs/OnThisPage/OnThisPage.stories.tsx
  graphql/index.ts
  graphql/queries/PageStructureByID.graphql
  graphql/queries/SectionContentByID.graphql
  graphql/queries/SimplePageByID.graphql
  graphql/queries/SimplePages.graphql
  pages/index.tsx
Labels: Type: Development, Type: Enhancement

#178 Add component layout
  components/layouts/Docs/Component.stories.tsx
  components/layouts/Docs/Component.test.tsx
  components/layouts/Docs/Component.tsx
  components/layouts/Docs/index.ts
  components/layouts/Docs/partials/StyledArticle.tsx
  components/layouts/Docs/partials/StyledBody.tsx
  components/layouts/Docs/partials/StyledContent.tsx
  components/layouts/Docs/partials/StyledMain.tsx
  components/layouts/Docs/partials/StyledMastheadWrapper.tsx
  components/layouts/Docs/partials/StyledOnThisPageWrapper.tsx
  components/layouts/Docs/partials/StyledPageWrapper.tsx
  components/layouts/Docs/partials/StyledSidebarWrapper.tsx
  components/layouts/Docs/partials/StyledTitle.tsx
  components/presenters/Docs/Footer/Footer.tsx
  components/presenters/Docs/Footer/partials/StyledFooter.tsx
  components/presenters/Docs/Masthead/partials/StyledMasthead.tsx
  components/presenters/Docs/OnThisPage/partials/StyledOnThisPage.tsx
  components/presenters/Docs/Sidebar/Sidebar.tsx
  components/presenters/Docs/Sidebar/SidebarMenu.tsx
Labels: Type: Development
