Repository Royal-Navy/design-system-docs, pull requests merged in 2021-08, with the labels that each got.

#192 ci(GHA): Add condition to set Contentful env
  .github/workflows/build_and_test_feature.yml
Labels: Type: Bug, Type: Devops

#193 Ci/dependabot
  .github/workflows/automerge.yml
  .github/workflows/build_and_test_feature.yml
Labels: Type: Enhancement, Type: Devops

#194 ci(Security): Enable dependabot
  .github/dependabot.yml
Labels: Type: Devops, Type: Security

#190 ci(GHA): Add branch deploy workflow
  .github/workflows/branch_deploy.yml
Labels: Type: Devops

#209 chore(Security): Update lock file
  yarn.lock
Labels: Type: Security

#215 test(Jest): Set global test environment to jsdom
  jest.config.js
  package.json
  yarn.lock
Labels: Type: Enhancement, Type: Development

#224 ci(E2E_tests): Capture screenshots for failed end to end tests
  .github/workflows/automerge.yml
  .github/workflows/build_and_test_feature.yml
  .github/workflows/build_and_test_master.yml
  cypress.json
Labels: Type: Enhancement, Type: Devops

#229 docs(Security): Add security policy
  SECURITY.md
Labels: Type: Devops, Docs: Readme, Type: Security

#227 docs(License): Add license
  LICENSE
  README.md
Labels: Type: Devops, Docs: Readme

#225 chore(Security): Change w3 url references to https
  components/presenters/Framework/Hero/Hero.tsx
  public/NavyDigitalServicesLogo.svg
  public/NelsonLogoClip.svg
  public/RNDSLogo.svg
  public/RNDSMobileLogo.svg
Labels: Type: Devops, Type: Security
