Repository Royal-Navy/design-system-docs, pull requests merged in 2021-05, with the labels that each got.

#109 test(Cypress): Fix plugins
  cypress/plugins/index.ts
  package.json
  yarn.lock
Labels: Bug

#110 Ci/e2e
  .github/workflows/build_and_test_feature.yml
  .github/workflows/build_and_test_master.yml
Labels: DevOps

#112 chore(Security): Bump dependencies flagged by `yarn audit`
  package.json
  yarn.lock
Labels: DevOps, Development

#108 ci(Release): Add manual release workflow
  .github/workflows/manual_release.yml
Labels: DevOps

#117 ci(Release): Update tokens in release workflows
  .github/workflows/manual_release.yml
  .github/workflows/release.yml
Labels: Bug, DevOps

#119 ci(Release): Drop v prefix for release version
  .github/workflows/manual_release.yml
  .github/workflows/release.yml
Labels: DevOps
