Repository Royal-Navy/design-system-docs, pull requests merged in 2021-03, with the labels that each got.

#54 feat(Components): Add Masthead presenter
  .github/workflows/build_and_test_feature.yml
  .github/workflows/build_and_test_master.yml
  a11y/index.test.tsx
  babel.config.js
  common/ComponentWithClass.ts
  common/index.ts
  components/presenters/Masthead/Masthead.stories.tsx
  components/presenters/Masthead/Masthead.test.tsx
  components/presenters/Masthead/Masthead.tsx
  components/presenters/Masthead/index.ts
  components/presenters/Masthead/partials/StyledButton.tsx
  components/presenters/Masthead/partials/StyledContent.tsx
  components/presenters/Masthead/partials/StyledMasthead.tsx
  components/presenters/Masthead/partials/StyledTitle.tsx
  jest.config.js
  jest/__mocks__/fileMock.js
  jest/globalSetup.js
  jest/setupTests.js
  package.json
  pages/index.tsx
  yarn.lock
Labels: Component, Development

#58 Add API Table component
  .gitignore
  components/presenters/ApiTable/ApiTable.stories.tsx
  components/presenters/ApiTable/ApiTable.test.tsx
  components/presenters/ApiTable/ApiTable.tsx
  components/presenters/ApiTable/ApiTableDefaultValue.tsx
  components/presenters/ApiTable/ApiTableDescription.tsx
  components/presenters/ApiTable/ApiTableFunctionParameter.tsx
  components/presenters/ApiTable/ApiTableItem.tsx
  components/presenters/ApiTable/index.ts
  components/presenters/ApiTable/partials/StyledBody.tsx
  components/presenters/ApiTable/partials/StyledBodyRow.tsx
  components/presenters/ApiTable/partials/StyledBodyRowItem.tsx
  components/presenters/ApiTable/partials/StyledBodyRowValue.tsx
  components/presenters/ApiTable/partials/StyledHeader.tsx
  components/presenters/ApiTable/partials/StyledHeaderRequired.tsx
  components/presenters/ApiTable/partials/StyledHeaderTitle.tsx
  components/presenters/ApiTable/partials/StyledHeaderType.tsx
  components/presenters/ApiTable/partials/StyledItem.tsx
  components/presenters/ApiTable/partials/StyledParameter.tsx
  components/presenters/ApiTable/partials/StyledParameterName.tsx
  components/presenters/ApiTable/partials/StyledParameterType.tsx
  components/presenters/ApiTable/partials/StyledParameters.tsx
  package.json
  yarn.lock
Labels: Component, Development

#56 feat(Components): Add Sidebar presenter
  components/presenters/Masthead/Masthead.stories.tsx
  components/presenters/Masthead/Masthead.test.tsx
  components/presenters/Masthead/Masthead.tsx
  components/presenters/Sidebar/Sidebar.stories.tsx
  components/presenters/Sidebar/Sidebar.test.tsx
  components/presenters/Sidebar/Sidebar.tsx
  components/presenters/Sidebar/SidebarMenu.tsx
  components/presenters/Sidebar/SidebarMenuItem.tsx
  components/presenters/Sidebar/index.tsx
  components/presenters/Sidebar/partials/StyledButton.tsx
  components/presenters/Sidebar/partials/StyledFrame.tsx
  components/presenters/Sidebar/partials/StyledHeader.tsx
  components/presenters/Sidebar/partials/StyledHomeLink.tsx
  components/presenters/Sidebar/partials/StyledNavLink.tsx
  components/presenters/Sidebar/partials/StyledNavList.tsx
  components/presenters/Sidebar/partials/StyledNavSection.tsx
  components/presenters/Sidebar/partials/StyledNavSectionTitle.tsx
  components/presenters/Sidebar/partials/StyledSidebar.tsx
  components/presenters/Sidebar/partials/StyledSidebarMenu.tsx
  components/presenters/Sidebar/partials/StyledSidebarMenuItem.tsx
  components/presenters/Sidebar/partials/StyledTitle.tsx
Labels: Component, Development

#57 feat(Components): Add Hero presenter
  components/presenters/ContentPanel/ContentPanel.tsx
  components/presenters/ContentPanel/LeftCol.tsx
  components/presenters/ContentPanel/RightCol.tsx
  components/presenters/ContentPanel/constants.ts
  components/presenters/ContentPanel/index.ts
  components/presenters/ContentPanel/partials/StyledContentPanel.tsx
  components/presenters/ContentPanel/partials/StyledLeftCol.tsx
  components/presenters/ContentPanel/partials/StyledRightCol.tsx
  components/presenters/Hero/Hero.stories.tsx
  components/presenters/Hero/Hero.test.tsx
  components/presenters/Hero/Hero.tsx
  components/presenters/Hero/index.ts
  components/presenters/Hero/partials/StyledIllustration.tsx
  components/presenters/Hero/partials/StyledLeftCol.tsx
  components/presenters/Hero/partials/StyledPageDescription.tsx
  components/presenters/Hero/partials/StyledPageTitle.tsx
Labels: Component, Development

#64 feat(Components): Add CodeBlock presenter
  components/presenters/CodeBlock/CodeBlock.stories.tsx
  components/presenters/CodeBlock/CodeBlock.test.tsx
  components/presenters/CodeBlock/CodeBlock.tsx
  components/presenters/CodeBlock/index.ts
  components/presenters/CodeBlock/partials/StyledCodeBlock.tsx
  components/presenters/CodeBlock/partials/StyledFilename.tsx
  components/presenters/CodeBlock/partials/StyledHeader.tsx
  components/presenters/CodeBlock/partials/StyledHighlight.tsx
  jest.config.js
  package.json
  yarn.lock
Labels: Component, Development

#66 Add LiveExample component
  components/presenters/ApiTable/ApiTable.stories.tsx
  components/presenters/ApiTable/ApiTableDefaultValue.tsx
  components/presenters/LiveExample/LiveExample.stories.tsx
  components/presenters/LiveExample/LiveExample.test.tsx
  components/presenters/LiveExample/LiveExample.tsx
  components/presenters/LiveExample/partials/StyledLiveExample.tsx
Labels: Component, Development

#67 feat(Pages): Render data from Contentful
  babel.config.js
  common/index.ts
  components/Post.tsx
  components/presenters/ApiTable/adapters/ApiTableAdapter.tsx
  components/presenters/CodeBlock/adapters/CodeBlockAdapter.tsx
  components/presenters/ContentPanel/adapters/ContentBlockAdapter.tsx
  components/presenters/ContentPanel/partials/StyledContentPanel.tsx
  components/presenters/ContentPanel/partials/StyledRightCol.tsx
  components/presenters/Hero/adapters/HeroAdapter.tsx
  components/presenters/Hero/partials/StyledPageDescription.tsx
  components/presenters/LiveExample/LiveExample.tsx
  components/presenters/LiveExample/adapters/LiveExampleAdapter.tsx
  components/presenters/LiveExample/partials/StyledHeader.tsx
  components/presenters/LiveExample/partials/StyledTitle.tsx
  components/presenters/Sidebar/partials/StyledFrame.tsx
  components/presenters/Sidebar/partials/StyledNavLink.tsx
  global.scss
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  services/contentful.ts
  yarn.lock
Labels: Development

#77 build(ESLint): Update configuration
  .eslintignore
  .gitignore
  components/adapters/ApiTableAdapter.tsx
  components/adapters/CodeBlockAdapter.tsx
  components/adapters/ContentBlockAdapter.tsx
  components/adapters/HeroAdapter.tsx
  components/adapters/LiveExampleAdapter.tsx
  package.json
  yarn.lock
Labels: DevOps, Development

#76 ci(GHA): Updating workflows
  .github/workflows/build_and_test_feature.yml
  .github/workflows/build_and_test_master.yml
  package.json
  scripts/check-fixup/index.js
  scripts/commitlint/index.js
  yarn.lock
Labels: DevOps

#78 feat(ContentBlockAdapter): Enable rich text media
  components/adapters/ApiTableAdapter.tsx
  components/adapters/CodeBlockAdapter.tsx
  components/adapters/ContentBlockAdapter.tsx
  components/adapters/HeroAdapter.tsx
  components/adapters/LiveExampleAdapter.tsx
  graphql/index.ts
  graphql/queries/SectionContent.graphql
Labels: Development

#80 ci(Sonarcloud): Add sonarcloud
  .github/workflows/build_and_test_feature.yml
  .github/workflows/build_and_test_master.yml
  package.json
  sonar-project.properties
  yarn.lock
Labels: DevOps

#84 feat(ApiTableAdapter): Render `defaultValue` JSON
  .gitignore
  components/adapters/ApiTableAdapter.tsx
  components/adapters/ContentBlockAdapter.tsx
  components/layouts/Framework/Framework.tsx
  components/presenters/ApiTable/ApiTableItem.tsx
  components/presenters/ApiTable/index.ts
  components/presenters/ContentPanel/partials/StyledContentPanel.tsx
  components/presenters/Section/Section.tsx
  components/presenters/Section/index.ts
  components/presenters/Section/partials/StyledSection.tsx
  components/presenters/Sidebar/Sidebar.tsx
  components/presenters/Sidebar/SidebarMenu.tsx
  graphql/index.ts
  pages/index.tsx
Labels: Development

#85 fix(Layout): Update masthead title
  components/layouts/Framework/Framework.tsx
Labels: Bug, Development

#86 fix(ApiTableAdapter): Add missing `p` tag for description
  components/adapters/ApiTableAdapter.tsx
  components/presenters/ApiTable/ApiTableItem.tsx
Labels: Bug

#87 fix(Contentful): Further reduce query complexity
  components/adapters/ContentBlockAdapter.tsx
  graphql/index.ts
  graphql/queries/PageStructure.graphql
  graphql/queries/SectionContent.graphql
  services/contentful.ts
Labels: Development

#88 fix(Sidebar): Style APITable content sections differently
  components/presenters/Sidebar/SidebarMenuItem.tsx
  components/presenters/Sidebar/partials/StyledNavLink.tsx
  pages/index.tsx
Labels: Bug
